version: "3"

services:
  identity_web_api:
    build:
        context: .
        dockerfile: Identity/Identity.WebAPI/Dockerfile
    ports:
        - 5001:5001
    environment:
        - ASPNETCORE_URLS=http://+:5001
  
  core_web_api:
    build:
        context: .
        dockerfile: Core/Core.WebAPI/Dockerfile
    ports:
        - 5002:5002
    environment:
        - ASPNETCORE_URLS=http://+:5002
    depends_on:
        - identity_web_api